name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: symfony
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_pgsql
          coverage: none

      - name: Install dependencies
        working-directory: ./symfony
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Wait for PostgreSQL
        run: sudo apt-get install -y postgresql-client && until pg_isready -h 127.0.0.1 -p 5432; do echo "Waiting for PostgreSQL..."; sleep 1; done

      - name: Run GrumPHP
        working-directory: ./symfony
        run: vendor/bin/grumphp run

      - name: Run tests
        working-directory: ./symfony
        env:
          DATABASE_URL: 'postgresql://symfony:symfony@127.0.0.1:5432/symfony'
        run: vendor/bin/phpunit
